### PR TITLE
focus: Add a way to enable more debug logging

### PR DESCRIPTION
**Pull request by algernon**
When `focus.debug` is set, the library will log far more verbosely, including all outgoing and incoming data, with converting to string being the only processing done on them.

This is to aid in debugging what's going on behind the scenes.

Screenshot from 2019-08-15 18-53-03

### CODE REVIEW

**Comment by algernon** [comment]
The way to set `focus.debug` is this (from the webtools console):

```javascript
Focus = require('@chrysalis-api/focus').default;
focus = new Focus();
focus.debug = true;
```

I originally wanted to add a new screen to Chrysalis, but in the end, decided against it for a number of reasons:
- Very few people would ever need to use it.
- Those who do, will be equally - if not more - comfortable with using the console of WebTools.
- The console also allows one to run any JS code, and as such, is much less limiting than a screen would have been.

**Comment by obra** [comment]
can we just add a checkbox on the advanced screen?

**Comment by algernon** [comment]
Yup, can do that. I'll prep a PR doing just that, too.

**Comment by obra** [comment]
I expect that most people who will be enabling this are people who don’t know what they’re doing and need our help

**Pull request merged**
